### ISSUE TITLE
File Transfer Failed

### ISSUE THREAD

**Issue by harsha-bongle** [gavinkendall/autoscreen#19]
When trying to transfer screenshot using 'File Transfer' button, getting  **File Transfer Failed** error.

Note: I successfully tested the connection with the sftp server before trying to transfer

![image](https://user-images.githubusercontent.com/73070698/159108700-c27e5b8d-8b04-4c27-8a6a-cc800521deb2.png)
![image](https://user-images.githubusercontent.com/73070698/159108866-99434b13-db0d-4948-b8df-f2d41d5ca3c9.png)

**Comment by gavinkendall** [comment]
Sorry. There could be so many different reasons why. Go to where you have your Screenshots Folder and look inside the "Auto Screen Capture\!autoscreen" folder. This is where the application keeps all of its important data files. There should be a folder in the "!autoscreen" folder named "debug" that might have a text file giving the error message. You can also edit the "application.xml" file (it's inside "!autoscreen\settings") to turn on DebugMode by setting the value from "False" to "True" then run the application and try again. This will write log files to "!autoscreen\logs" which might give us a clue as to why it's not uploading the file to the SFTP server.

The parent of your Screenshots Folder should have a folder named "!autoscreen":
![Screenshot on 2022-03-19 at 09-22-57 841](https://user-images.githubusercontent.com/7693885/159123020-85fce474-2abc-4f6a-b7fa-6f16ac0a626d.jpeg)

From here you can see all of application's data files for its components:
![Screenshot on 2022-03-19 at 09-23-55 334](https://user-images.githubusercontent.com/7693885/159123021-0bfdbd3d-be3e-4865-8faf-adfebf3acd45.jpeg)

This is where to set DebugMode for the application so it writes log files to "!autoscreen\logs":
![Screenshot on 2022-03-19 at 09-25-34 562](https://user-images.githubusercontent.com/7693885/159123022-54c670e2-abf2-4d31-a775-c9886f8b5a9d.jpeg)

**Comment by harsha-bongle** [comment]
@gavinkendall Thank you for your quick response.

As suggested by you, I looked at the logs.  I suspect upload is failing due to file name (Ex:  "Program Manager (2022-03-19 19-51-14.637).jpeg") 

![log](https://user-images.githubusercontent.com/73070698/159131040-8dcbfe24-5cbf-4a60-a173-275a5278ce13.jpg)


I set up the SFTP server on an AWS EC2 instance which is running Ubuntu 20.04. 


Note: When I tried to copy a screenshot file from my local windows10 machine using **WinSCP** tool , it succeded.

![WinSCP](https://user-images.githubusercontent.com/73070698/159131052-ac226a5c-f93b-4d5c-a586-a4af62674773.jpg)

**Comment by harsha-bongle** [comment]
@gavinkendall I would like to mention that I am a beginner when it comes to Linux/Ubuntu. I apologize  if I missed any minor thing

**Comment by gavinkendall** [comment]
Is it successfully uploading if you use a simple name for each screenshot? Such as just naming it "%date%_%time%.%format%" without any spaces?

**Comment by gavinkendall** [comment]
ASC can run WinSCP if that helps. I wrote an article about it a while ago:
https://sourceforge.net/p/autoscreen/blog/2020/11/sftp-with-winscp-and-auto-screen-capture/

It explains how to setup SFTP in Linux and use WinSCP with Auto Screen Capture.

**Comment by harsha-bongle** [comment]
@gavinkendall   When I created an SFTP (transfer family) managed server on AWS, I was able to transfer the screenshots successfully.

So I assume the reason for failure earlier was maybe the SFTP server I set up on the EC2 instance was not configured properly.

I am closing this issue.


Thank You very much for your quick response
