### ISSUE TITLE
"Optimize Screen Capture" 0% tolerance does not work

### ISSUE THREAD

**Issue by VelocityRa** [gavinkendall/autoscreen#34]
I would expect there to be an optimize option that checks every pixel and if _any_ is different, does not reject it.

Setting 0% tolerance would in theory do that (?) but currently it makes it not reject any frames even if they are the exact same.
Setting it to 1% is not acceptable for me, since it sees frames with small changes as duplicates (whereas I do want it to capture those frames too).

**Comment by VelocityRa** [comment]
Maybe do a `Math.Ceiling()` before casting to `int` here:
https://github.com/gavinkendall/autoscreen/blob/d36e04acef490fdacbe4492faaf5e363c2284d1a/modules/screenshots/ScreenshotCollection.cs#L324

0% tolerance would work as expected then, instead of the few pixels/% getting lost in the cast.

**Comment by gavinkendall** [comment]
Please try with 2.5.1.5
https://github.com/gavinkendall/autoscreen/releases/tag/v2.5.1.5

**Comment by gavinkendall** [comment]
By the way I'm shutting down the Auto Screen Capture project so there will be no more updates after December 2022.

**Comment by VelocityRa** [comment]
Ok, thanks for your work.
I'm guessing you'll just Archive the repo and not delete it? Maybe someone else will pick it up.

**Comment by gavinkendall** [comment]
Yes. I'm not going to delete anything. I'm just taking a break from open source development so I'm going to leave the repository as it is and let others fork from it.
