### ISSUE TITLE
Screen Capture to Text Recognition

### ISSUE THREAD

**Issue by judohighlights** [gavinkendall/autoscreen#9]
Hi Gavin,

Thanks for getting back to me on the comments on YouTube. I've got a lofty idea and it's something that a number of developers on Fiverr have told me is not possible - although I'm stubborn despite my zero experience with coding. To put it simply, if you type UFC in google you get the UFC schedule. All I want to do at this point is screen capture the schedule and have the information copied and pasted somewhere. Why you may ask? I'm trying to build an app that uses this information, however, apparently crawlers and API's will be blocked/won't work, which is why I'm looking at screen capture technology (OCR?).

Would love to hear your thoughts, and at this point I'm willing to just offer 50% of the revenue to whoever can build the app. 

Regards,

Sam

**Comment by gavinkendall** [comment]
Hi Sam,

I think ShareX comes with an OCR tool. Auto Screen Capture 2.3.3.2 (which you can get either from https://github.com/gavinkendall/autoscreen/releases/tag/v2.3.3.2 or https://sourceforge.net/projects/autoscreen/files/2.3.3.2/) can almost do the entire process for you with some preparation. So, assuming you're using Chrome as your Web browser, you can ...

1) Open Google Chrome
2) Auto Screen Capture 2.3.3.2 (this is the latest version as of today so make sure you're using this version or newer for this exercise to work properly)
3) Go to Configure menu in top right corner and select "Change Screen"
4) Change the Component to "Active Window" (and change the Name to "Active Window") and click OK
5) In the Setup tab change Interval to 10 seconds, check the checkbox where you see "limit" and give "limit" a value of 1
6) In the Setup tab check the "Capture only if the title contains ..." checkbox and put "Google Search" into the text field
7) In the Setup tab (you might have to scroll down a bit) click on the drop-down control for "Application Focus" and select "chrome"
8) In the Editors tab (it's to the right of the Regions tab so you should see Setup, Screenshots, Screens, Regions, and Editors) click on the green plus button
9) Name the editor "Chrome"
10) Put "C:\Program Files\Google\Chrome\Application\chrome.exe" for the Application
11) Change the Arguments to say "https://www.google.com/search?q=ufc" and click OK to make the new Editor
12) In the Triggers tab (it's the last tab so you should see Editors, Schedules, Tags, and finally Triggers) click on the green plus button
13) Select "Application Startup" for the Condition, "Run Editor" for the Action, and "Chrome" for the Editor then click OK
14) Click on the green plus button again to make a new Trigger
15) Select "Application Startup" for the Condition and "Start Screen Capture" for the Action then click OK
16) Close Auto Screen Capture

If everything is setup correctly what should happen whenever you run Auto Screen Capture is it will open Chrome to the search results for UFC in Google Search and a screenshot of those search results will be taken after 10 seconds (allowing you to alter the view as needed - maybe even just leave Chrome maximized for this exercise).

Gavin
